version: '3'

output: prefixed
silent: true

vars:
  pwd:
    sh: pwd

includes:
  docker: tasks/docker.yml
  atlas: tasks/atlas.yml
  frontend: tasks/frontend.yml
  nginx: tasks/nginx.yml
  security: tasks/security.yml

tasks:
  i:
    cmds:
      - task: 'atlas:install'
  a:
    cmds:
      - task: 'atlas:package'
