version: '3'

vars:
  name:
    sh: pom-name
  js: batch.js

tasks:
  package:
    desc: compile & bundle the project
    cmds:
      - atlas-mvn package -D reconquest.batch.js={{ .js }}
    deps: [target_eclipse]

  enable_debug:
    cmds:
      - >
        curl -s -u admin:admin -X PUT -d "" -H "Content-Type: application/json" \
         http://bitbucket.local:7990/rest/api/latest/logs/logger/com.ngs.stash.externalhooks/debug

  install:
    desc: compile and install current version
    cmds:
      - task: package
      - task: enable_debug
      - stacket --uri http://admin:admin@bitbucket.local:7990/ addons install target/{{ .name }}.jar

  eclipse:
    desc: prepare eclipse project
    cmds:
      - atlas-mvn eclipse:clean
      - atlas-mvn eclipse:eclipse -DoutputDirectory=./target/eclipse -DdownloadJavadocs=true -DdownloadSources=true

  target_eclipse:
    cmds:
      - task: eclipse
    status:
      - test -d target/eclipse

  compile:
    desc: compile code
    cmds:
      - atlas-mvn compile

