version: '3'

vars:
  version: 6.2.0
  dir:
    sh: readlink -f docker
  image: atlassian/bitbucket-server:{{ .version }}

tasks:
  run:
    desc: start docker container with bitbucket
    cmds:
      - mkdir -p {{ .dir }}/{{ .version }}
      - echo "starting {{ .image }}"
      - docker run -it --rm --name "{{ .version }}.bitbucket"
        -p 7990:7990
        -p 7999:7999
        --add-host=marketplace.atlassian.com:127.0.0.1
        -v {{ .dir }}/{{ .version }}:/var/atlassian/application-data/bitbucket
        {{ .image }}
  clean:
    desc: clean up aeh-* docker resources
    cmds:
      - echo "*** removing docker containers"
      - docker ps -a --filter 'name=aeh-*' --format {{`'{{.Names}}'`}}
        | xargs -n1 --verbose --no-run-if-empty docker rm -f
      - echo "*** removing docker volumes"
      - docker volume ls -q --filter 'name=aeh-*'
        | xargs -n1 --verbose --no-run-if-empty docker volume rm
      - echo "*** removing docker networks"
      - docker network ls -q --filter 'name=aeh-*' --format {{`'{{.Name}}'`}}
        | xargs -n1 --verbose --no-run-if-empty docker network rm
